=== lkishalmi/incubator-netbeans/java/gradle/src/org/netbeans/modules/gradle/actions/action-mapping.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT actions (action*,apply-for*)>
<!ELEMENT apply-for (action+)>
<!ELEMENT action (args?, reload?)>
<!ELEMENT reload (args?)>
<!ELEMENT args (#PCDATA)>

<!ATTLIST apply-for plugins CDATA #REQUIRED>
<!ATTLIST reload rule (NEVER|DEFAULT|ALWAYS|ALWAYS_ONLINE) "DEFAULT">
<!ATTLIST action name CDATA #REQUIRED>
<!ATTLIST action displayName CDATA #IMPLIED>
<!ATTLIST action repeatable (false|true) "true">
<!ATTLIST action priority CDATA #IMPLIED>

=== lkishalmi/incubator-netbeans/groovy/gradle.java/src/org/netbeans/modules/gradle/java/action-mapping.xml
<?xml version="1.0"?>
<!DOCTYPE actions SYSTEM "action-mapping.dtd">
<actions>
    <apply-for plugins="java">
        <action name="test.single">
            <args>--rerun-tasks test --tests ${selectedMethod}</args>
        </action>
        <action name="run.single.method">
            <args>--rerun-tasks test --tests ${selectedMethod}</args>
        </action>
        <action name="debug.single.method">
            <args>--rerun-tasks test --debug-jvm --tests ${selectedMethod}</args>
        </action>
        <action name="debug.test.single">
            <args>--rerun-tasks test --debug-jvm --tests ${selectedMethod}</args>
        </action>

        <action name="javadoc">
            <args>javadoc</args>
        </action>

        <action name="debug.fix" repeatable="false">
            <args>-offline --no-rebuild ${affectedBuildTasks}</args>
            <reload rule="NEVER"/>
        </action>

        <action name="compile.single" repetable="false">
            <args>--offline --no-rebuild ${affectedBuildTasks}</args>
            <reload rule="NEVER"/>
        </action>

        <action name="run.single">
            <args>-PrunClassName=${selectedClass} runSingle</args>
        </action>

        <action name="debug.single">
            <args>-PrunClassName=${selectedClass} runSingle --debug-jvm</args>
        </action>
    </apply-for>

    <apply-for plugins="application">
        <action name="run">
            <args>run</args>
        </action>

        <action name="debug">
            <args>run --debug-jvm</args>
        </action>
    </apply-for>

    <apply-for plugins="java-base,scala-base,com.github.lkishalmi.gatling">
        <action name="build">
            <args>gatlingClasses</args>
        </action>
        <action name="rebuild">
            <args>clean gatlingClasses</args>
        </action>
        <action name="run">
            <args>gatlingRun</args>
        </action>
        <action name="run.single">
            <args>gatlingRun-${selectedClass}</args>
        </action>
    </apply-for>
</actions>

=== lkishalmi/incubator-netbeans/java/gradle/test/unit/src/org/netbeans/modules/gradle/actions/action-mapping.xml
<?xml version="1.0"?>
<!DOCTYPE actions SYSTEM "action-mapping.dtd">
<actions>
    <action name="clean">
        <args>clean</args>
    </action>

    <action name="build">
        <args>build</args>
    </action>

    <action name="rebuild">
        <args>clean build</args>
    </action>

    <action name="test">
        <args>--rerun-tasks test</args>
    </action>

    <action name="download.javadoc">
        <reload rule="ALWAYS_ONLINE">
            <args>-PdownloadJavadoc={0}</args>
        </reload>
    </action>

    <action name="download.sources">
        <reload rule="ALWAYS_ONLINE">
            <args>-PdownloadSources={0}</args>
        </reload>
    </action>

    <action name="download.sourcesanddoc">
        <reload rule="ALWAYS_ONLINE">
            <args>-PdownloadSources={0} -PdownloadJavadoc={0}</args>
        </reload>
    </action>

    <apply-for plugins="java">
        <action name="test.single">
            <args>--rerun-tasks test -tests {0}</args>
        </action>

        <action name="debug.test.single">
            <args>--rerun-tasks test --debug-jvm --tests {0}</args>
        </action>

        <action name="javadoc">
            <args>javadoc</args>
        </action>

        <action name="debug.fix" repeatable="false">
            <args>-offline --no-rebuild {0}</args>
            <reload rule="NEVER"/>
        </action>
    </apply-for>

    <apply-for plugins="application">
        <action name="run">
            <args>run</args>
        </action>

        <action name="debug">
            <args>run --debug-jvm</args>
        </action>
    </apply-for>

    <apply-for plugins="com.github.lkishalmi.gatling">
        <action name="run">
            <args>gatling</args>
        </action>
    </apply-for>

    <apply-for plugins="root">
        <action name="clean">
            <args>clean</args>
        </action>

        <action name="build">
            <args>assemble</args>
        </action>

        <action name="rebuild">
            <args>clean assemble</args>
        </action>
    </apply-for>

    <apply-for plugins="war">
        <action name="run">
            <args>war</args>
        </action>
    </apply-for>
</actions>
